Unable to find image 'quay.io/biocontainers/python:3.9--1' locally
3.9--1: Pulling from biocontainers/python
c1a16a04cedd: Pulling fs layer
4ca545ee6d5d: Pulling fs layer
5f7a6762e5ca: Pulling fs layer
4ca545ee6d5d: Download complete
c1a16a04cedd: Download complete
c1a16a04cedd: Pull complete
4ca545ee6d5d: Pull complete
5f7a6762e5ca: Verifying Checksum
5f7a6762e5ca: Download complete
5f7a6762e5ca: Pull complete
Digest: sha256:d97d2b329b4e44d2e07a9737ba348b185d6a47f34fba0ef301d44d11669cac60
Status: Downloaded newer image for quay.io/biocontainers/python:3.9--1
Collecting pandas
  Downloading pandas-2.3.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)
Collecting numpy
  Downloading numpy-2.0.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (19.5 MB)
Collecting scipy
  Downloading scipy-1.13.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
Collecting python-dateutil>=2.8.2
  Downloading python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
Collecting six>=1.5
  Downloading six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: six, tzdata, pytz, python-dateutil, numpy, scipy, pandas
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Successfully installed numpy-2.0.2 pandas-2.3.2 python-dateutil-2.9.0.post0 pytz-2025.2 scipy-1.13.1 six-1.17.0 tzdata-2025.2
